### PR TITLE
Develop

### LINKED ISSUE #53: Export to Thebeau Matlab file column label string incorrect
Here is an example of an item label in the export file:

DSMLABEL{1,1} = 'StringProperty [value: Rule 2]';

Upon import, the entire string 'StringProperty [value: Rule 2]' becomes the new label when it was originally 'Rule 2'.  Modifying the export file to be written like

DSMLABEL{1,1} = StringProperty [value: 'Rule 2'];

retains the original column labels.

Note the attached file was changed as Git does not support .m files.
[Export2.txt](https://github.com/ajcarney/DSMEditor/files/14773493/Export2.txt)

### LINKED ISSUE #55: Multi-zoom adding a new row with new connections does not fully append back to main view
While running test DSMED-33, step 13, there was a failure. Here's what was happening:
Multizoom to default-default domain
Add a new row/col item Z
Append the following connectivity:
(Z,A), (Z,G), (Z,E), (E,Z)

When applying this back to the main view the following connectivity was missing:
(E,Z)
[DSMED-33_defect_dsm_files.zip](https://github.com/user-attachments/files/18308963/DSMED-33_defect_dsm_files.zip)

### PR DESCRIPTION
**Pull request by ajcarney**
# Changes
* Added ART1 algorithm for clustering (a personal experiment, doesn't cluster very well but does find similar elements)
* Fixed bug in Thebeau algorithm so I believe it now behaves the same as the actual
* Fixed PNG export where scrollbar could be seen in fast render export
* Added searchable comboboxes everywhere you are asked for an item
* added more keyboard shortcuts (ctrl-s to save, <enter> to add changes to change-stack on add items popup, etc)
* Popup windows should now open on their parent window (noticeable only for dual monitor setups when moving main window to secondary display)
* Fixed #53 
* Fixed submit bug report button
* Other refactoring of GUI code (functionality should remain same except for changes listed)
* Fixed #55, also fixed import Asymmetric matrix zoom (groups not brought in correctly)

### CODE REVIEW

File: src/main/java/Matrices/ClusterAlgorithms/ART1.java [hunk 1]
```diff
@@ -0,0 +1,239 @@
...
+    }
+
+
+    /**
+     * returns magnitude of vector defined as sum of all elements
+     * @param v vector
+     * @return magnitude
+     */
+    private double vectorMagnitude(ArrayList<Double> v) {
+        int sum = 0;
```
Comment (ainGitHub) [inline src/main/java/Matrices/ClusterAlgorithms/ART1.java:110]: Here may occur int overhead, may be need use other structure, BigInteger for example

File: src/main/java/Matrices/ClusterAlgorithms/ART1.java [hunk 2]
```diff
@@ -0,0 +1,239 @@
...
+            } else {
+                newPrototype.add(0.0);
+            }
+        }
+
+    }
+
+
+    private void updatePrototype(int prototypeIndex) {
+        ArrayList<Integer> memberIndices = new ArrayList<>();  // contains list of the items in this prototype
```
Comment (ainGitHub) [inline src/main/java/Matrices/ClusterAlgorithms/ART1.java:133]: Usually in left side write List<Integer>, not concrete implementation

File: src/main/java/Matrices/ClusterAlgorithms/ART1.java [hunk 3]
```diff
@@ -0,0 +1,239 @@
...
+    ArrayList<Grouping> prototypeGroups;
+
+
+    public ART1(SymmetricDSMData inputMatrix) {
+        matrix = inputMatrix.createCopy();
+        sortedItems = new ArrayList<>(matrix.getRows());
+
+        numItems = matrix.getRows().size();
+        adjacencyMatrix = new ArrayList<>();
+        for(int row = 0; row < numItems; row++) {
```
Comment (ainGitHub) [inline src/main/java/Matrices/ClusterAlgorithms/ART1.java:35]: Seems like not formatting in file

Comment (ainGitHub) [reply src/main/java/Matrices/ClusterAlgorithms/ART1.java:35]: opt + cmd + L in mac

File: src/main/java/Matrices/ClusterAlgorithms/Thebeau.java [hunk 4]
```diff
@@ -0,0 +1,304 @@
...
+            }
+
+
+            String startTime = String.valueOf(Duration.between(absStart, start).toMillis());
+            String elapsedTime = String.valueOf(Duration.between(start, Instant.now()).toMillis());
+            debugString.append(i).append(",").append(startTime).append(",").append(elapsedTime).append(",").append(newCoordinationScore).append("\n");
+        }
+
+        if(debug) {
+            System.out.println(debugString);
```
Comment (ainGitHub) [inline src/main/java/Matrices/ClusterAlgorithms/Thebeau.java:297]: May be need use some logger, like Slf4j or Logger, they more useful and simple to use

**Comment by dtcarney741** [comment]
I have executed the Qase verification plan (see attached). Ready for release.
[DSMED-Test+run+2025_03_27.pdf](https://github.com/user-attachments/files/19522015/DSMED-Test%2Brun%2B2025_03_27.pdf)
